Feature undo last entry
CSC207-2022F-UofT/course-project-mewdy pull request #19
Opened 2022-11-17 02:54 UTC by dozysushi

Undo the last entry.

2022-11-18 05:27 UTC, Bensonwu02 requested changes
You can delete the overloaded constructor for the response model because I don't think you are using it?

I would make a custom exception class to handle the case where the metric contains 0 datapoints. Let me know if you're unsure about how to do this.

2022-11-19 05:00 UTC, Wizard603 requested changes
Summary:
- Remove the idea and gradle project files
- Narrow Exception handling to more specific cases
- Consider what happens when null is returned from getDataPointList

also you should clean up the unnecessary new lines for better readability

2022-11-19 05:00 UTC, Wizard603 commented on gradlew.bat
> +:omega
Can you remove the .idea and gradle related files from you commits.

2022-11-19 05:00 UTC, Wizard603 commented on src/main/java/UseCases/EntryUndo.java
> +            } catch (Exception e) {
Maybe replace with a custom Exception or use a existing more specific one

2022-11-19 05:00 UTC, Wizard603 commented on src/main/java/UseCases/EntryUndo.java
> +            ArrayList<DataPoint> deletedMetric = this.metricStorage.getDataPointList(metricName);
note getDataPointList can return null

2022-11-19 05:00 UTC, Wizard603 commented on src/main/java/UseCases/EntryUndo.java
> +            ArrayList<DataPoint> deletedMetric = this.metricStorage.getDataPointList(metricName);
consider adding a null pointer exception or dealing with the empty list situation in some other way. Likely they should not be able to undo anything in this case

2022-11-20 23:45 UTC, tylerkj1209 approved these changes

2022-11-21 14:29 UTC, dozysushi commented
> You can delete the overloaded constructor for the response model because I don't think you are using it?
> 
> I would make a custom exception class to handle the case where the metric contains 0 datapoints. Let me know if you're unsure about how to do this.

I deleted unused method in response model, will add a exception class later.

2022-11-21 14:35 UTC, dozysushi commented on gradlew.bat
> +:omega
> Summary:
> 
> * Remove the idea and gradle project files
> * Narrow Exception handling to more specific cases
> * Consider what happens when null is returned from getDataPointList
> 
> also you should clean up the unnecessary new lines for better readability

I deleted the idea and gradle, working on exception class, right now I use try to fix the problem

2022-11-21 14:36 UTC, dozysushi commented on src/main/java/UseCases/EntryUndo.java
> +            ArrayList<DataPoint> deletedMetric = this.metricStorage.getDataPointList(metricName);
working on exception class

2022-11-21 16:35 UTC, Wizard603 approved these changes

2022-11-21 16:37 UTC, Bensonwu02 approved these changes

2022-11-21 16:56 UTC, dozysushi commented
I think everything is working right now. I fix all the problems from comment.

2022-11-21 17:00 UTC, merged