[Added Feature] Data Logging
CSC207-2022F-UofT/course-project-mewdy pull request #22
Opened 2022-11-17 03:19 UTC by tylerkj1209

This is the code for logging data. The DataLogger use case is now functional in all test cases. A DataPoint can be logged to a metric in metric storage using the DataLoggerController. This code is necessary for inputting data into the program so that it can be displayed later on. The DataLogger use case accesses the MetricStorage through an interface and tries to add a specified datapoint to a specified metric. If it succeeds, the presenter gets a success message that the data point was successfully added, while if it fails, a fail message is returned. The test cases are adding data to metric storages that are missing metrics, having incorrect metric names, having correct metric names, and having multiple different metrics. I also run tests that make sure that adding a datapoint on the same day as another datapoint does not overwrite it or add more datapoints.

2022-11-18 05:04 UTC, Bensonwu02 requested changes
For DataLoggerController:
Should not have metric storage and presenter as instance variables. You aren't using the presenter so that won't be needed. For metric storage, we pass it into constructor of the use case interactor instead.

For DataLoggerRequestModel:
Shouldn't have metric storage as a stored variable. Only transient data needed to fulfill use case (input from user). See above for how to pass in metric storage.

For presenter and responsemodel:
I don't think you necessarily need responsemodel.message. You can just directly write the string "Successfully added datapoint" in the presenter's prepareSuccessView method.
 For the fail cases, you already directly pass in a formatted string so I don't think you will need the overloaded constructor for your response model that only takes in a string. I see that you use the overloaded constructor to make a new response model in the return statement of your successview method. I think you can just return a String of the formatted sentence instead of a response model. 

DataLogger:
We don't have text entries anymore so you can delete that from your documentation of logDataPoint method.

Exception thrown for metric does not exist:
I think it might be good to make a custom exception class for this rather than catch all exceptions. There could be some cases where we don't want to catch an exception if the code breaks.

2022-11-18 23:59 UTC, Wizard603 approved these changes
I mostly agree with Benson's comments. Additionally you should make more specific exceptions to prevent over catching of errors. To elaborate you may run into a situation where a null is given and you catch the error but don't crash resulting in a null being written where it should not be .

2022-11-18 23:59 UTC, Wizard603 commented on src/main/java/UseCases/DataLogger.java
> +            String lastDate = null;
No need to initialize lastDate and todayDate with null. This might cause some errors if it is not reassigned later

2022-11-18 23:59 UTC, Wizard603 commented on src/main/java/UseCases/DataLogger.java
> +        catch (Exception e){
Change the Exception to be a more specific version. Since the date formatting can cause a Parse exception

2022-11-18 23:59 UTC, Wizard603 commented on src/main/java/Entities/MetricStorageInterface.java
>      Metric getMetric(String metricName) throws Exception;
Change Exception by making a new more specific exception to prevent catching all unrelated errors.

2022-11-18 23:59 UTC, Wizard603 commented on src/main/java/Main.java
>  import java.util.Date;
We are no longer using util.Date

2022-11-18 23:59 UTC, Wizard603 commented on src/main/java/UseCases/DataLoggerInputBoundary.java
> +    DataLoggerResponseModel logDataPoint(DataLoggerRequestModel requestModel) throws Exception;
Make more specific Exception

2022-11-19 00:04 UTC, Wizard603 commented
Also look into my branch (import-data) for the latest changes to the entities package since some of the changes affect your code. I think the main one is the dataPoint.getDate() method returning a string rather than a LocalDateTime

2022-11-19 05:30 UTC, Bensonwu02 approved these changes

2022-11-19 14:55 UTC, cdsgibson approved these changes
I also mostly agree with Benson and Kyle's comments, especially those concerning the request model and the custom exceptions.

2022-11-19 20:26 UTC, merged

2022-11-21 17:00 UTC, dozysushi commented
Can you please add more documentation?