Feature delete metric
CSC207-2022F-UofT/course-project-mewdy pull request #56
Opened 2022-12-02 16:36 UTC by cdsgibson

- Modified the "create" methods in MetricDelController and MetricDelInputBoundary to "deleteMetric"
- replaced instances of "create" with "deleteMetric"
- fixed the Java Doc for deleteMetric  in MetricDelController
- added setUp to MetricDeleterTest

2022-12-02 21:56 UTC, craftedswift commented on src/main/java/presenters/MetricDelOutputBoundary.java
> +public interface    MetricDelOutputBoundary {
is the extra indentation a typo?

2022-12-02 21:56 UTC, craftedswift requested changes
fix the typo in the metricdecl output boundary

2022-12-03 02:31 UTC, cdsgibson commented on src/main/java/presenters/MetricDelOutputBoundary.java
> +public interface    MetricDelOutputBoundary {
Yes, it is, my bad. I will fix it.

2022-12-03 07:08 UTC, craftedswift approved these changes
looks good!

2022-12-03 18:41 UTC, Bensonwu02 approved these changes
looks good. thanks for making those changes.

2022-12-04 16:03 UTC, Wizard603 approved these changes
Glad to see the metricDeleter is no longer called metricCreator

2022-12-04 16:05 UTC, merged