Refactoring and final javadoc additions
CSC207-2022F-UofT/course-project-mewdy pull request #62
Opened 2022-12-08 21:23 UTC by Bensonwu02

This pull request contains
- final javadoc additions
- updated README
- case handled for non-numerical data input for goal setting and add metric
- addition of 'example metrics' folder for more example data.

2022-12-08 21:27 UTC, craftedswift commented on src/main/java/models/SetGoalRequestModel.java
> +     */
for java doc make sure there is a space between the method description and the @param/@return

2022-12-08 21:29 UTC, craftedswift commented on src/main/java/presenters/MetricSumViewModel.java
> +
for java doc make sure there is a space between the method description and the @param/@return

2022-12-08 21:30 UTC, craftedswift commented on src/main/java/use_cases/GoalSetter.java
> +     * Method for setting goal.
for java doc make sure there is a space between the method description and the @param/@return

2022-12-08 21:30 UTC, tylerkj1209 approved these changes, later dismissed
Thank you for altering the fail view message for dataLogger to more clearly match with the actual exception being raised by the code. I see no issues with this pull request. Lots of good reworking of the documentation.

2022-12-08 21:30 UTC, craftedswift commented on src/main/java/screens/ChooseMetricSumScreen.java
> +     * @param viewModel represents view model from which this method extracts information to construct
for java doc make sure there is a space between the method description and the @param/@return

2022-12-08 21:31 UTC, craftedswift commented on src/main/java/use_cases/MetricDelInputBoundary.java
> +     *
Missing method description (my bad)

2022-12-08 21:35 UTC, Bensonwu02 commented on src/main/java/models/SetGoalRequestModel.java
> +     */
resolved

2022-12-08 21:36 UTC, Bensonwu02 commented on src/main/java/use_cases/GoalSetter.java
> +     * Method for setting goal.
resolved

2022-12-08 21:36 UTC, Bensonwu02 commented on src/main/java/screens/ChooseMetricSumScreen.java
> +     * @param viewModel represents view model from which this method extracts information to construct
resolved

2022-12-08 21:38 UTC, Bensonwu02 commented on src/main/java/use_cases/MetricDelInputBoundary.java
> +     *
resolved

2022-12-08 21:39 UTC, Bensonwu02 commented on src/main/java/use_cases/SetGoalInputBoundary.java
> +     *
resolved

2022-12-08 21:40 UTC, Bensonwu02 commented
Made changes in accordance with sanford's comments

2022-12-08 21:48 UTC, Wizard603 requested changes
capitalize final variables

2022-12-08 21:48 UTC, Wizard603 commented on README.md
>  - run Main.java
Maybe mention there is a downloadable jar file in the releases tab

2022-12-08 21:48 UTC, Wizard603 commented on src/main/java/controllers/DataExportController.java
> +    private final DataExportInputBoundary inputBoundary;
this is final so it should be all caps

2022-12-08 21:48 UTC, Wizard603 commented on src/main/java/controllers/DataImportController.java
> +    private final DataImportInputBoundary inputBoundary;
capitalize final variables

2022-12-08 21:48 UTC, Wizard603 commented on src/main/java/controllers/EntryUndoController.java
> +    private final EntryUndoInputBoundary entryUndo;
capitalize final variables

2022-12-08 21:48 UTC, Wizard603 commented on src/main/java/entities/DataPoint.java
> +    private final DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
capitalize final variables

2022-12-08 21:52 UTC, Bensonwu02 commented on src/main/java/controllers/DataExportController.java
> +    private final DataExportInputBoundary inputBoundary;
only static variables are caps

2022-12-08 21:53 UTC, Bensonwu02 commented on src/main/java/controllers/DataImportController.java
> +    private final DataImportInputBoundary inputBoundary;
same as above

2022-12-08 21:53 UTC, Bensonwu02 commented on src/main/java/entities/DataPoint.java
> +    private final DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
same as above

2022-12-08 21:56 UTC, Bensonwu02 commented on README.md
>  - run Main.java
done

2022-12-08 21:58 UTC, Wizard603 approved these changes, later dismissed
apparently static finals can be non capitalized

2022-12-08 21:58 UTC, Wizard603 commented on src/main/java/use_cases/DataImporter.java
> +        } catch (RuntimeException | ParseException e) {
Thank you for making the message more clear

2022-12-08 22:22 UTC, Wizard603 approved these changes
Good catch on the metric names

2022-12-08 23:47 UTC, craftedswift approved these changes

2022-12-09 01:45 UTC, dozysushi approved these changes

2022-12-09 01:45 UTC, merged